# Generated by Django 4.2.30 on 2026-05-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('residential_cleaner', 'Residential Cleaner'), ('commercial_cleaner', 'Commercial Cleaner'), ('team_lead', 'Team Lead'), ('flex_position', 'Flexible / Any Open Position')], max_length=40)),
                ('previous_experience', models.TextField(blank=True)),
                ('motivation', models.TextField()),
                ('flexible_hours', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
