# Generated by Django 4.2.30 on 2026-07-22

from django.core.validators import FileExtensionValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_careerapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerapplication",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Optional. PDF, DOC, or DOCX; maximum 5 MB.",
                upload_to="resumes/%Y/%m/",
                validators=[FileExtensionValidator(allowed_extensions=["pdf", "doc", "docx"])],
            ),
        ),
    ]
