# Generated by Django 4.2.30 on 2026-07-31 14:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_careerapplication_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('before_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('after_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'gallery session',
                'verbose_name_plural': 'gallery sessions',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
