# Generated by Django 4.2.30 on 2026-07-31 15:25

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_gallerysession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional. PDF, DOC, or DOCX; maximum 5 MB.', max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='resume'),
        ),
    ]
