# Generated by Django 4.2.30 on 2026-08-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_careerapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='checklist_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Home / Residential'), ('commercial', 'Business / Commercial')], default='residential', max_length=20),
        ),
    ]
